import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
    FileText, Download, Clock, ChevronDown, ChevronUp,
    TrendingDown, TrendingUp, Minus, CheckCircle, AlertTriangle
} from 'lucide-react';
import { MOCK_ANALYSIS_RESULT, ANALYSIS_HISTORY, RISK_COLORS } from '../utils/mockData';

// ─── Executive Clinical Report ───────────────────────────────────────────────

const ExecutiveClinicalReport: React.FC = () => {
    const result = MOCK_ANALYSIS_RESULT;
    const criticalDrug = result.drugs.find(d => d.severity === 'critical') || result.drugs[0];
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const handleDownload = () => {
        const content = `
PHARMAGUARD EXECUTIVE CLINICAL SUMMARY
=======================================
Date: ${today}
Patient / Sample ID: ${result.sampleId}
Engine Version: v2.4.0  |  CPIC Version: CPIC v24.2
Total Variants Analysed: ${result.totalVariants}
Genes Assessed: ${result.analyzedGenes.join(', ')}

OVERALL RISK SCORE: ${result.overallRiskScore}/100

KEY RISK DRUG
─────────────
Drug: ${criticalDrug.drug}
Risk Level: ${criticalDrug.riskLevel.toUpperCase()}
Severity: ${criticalDrug.severity.toUpperCase()}
Confidence: ${criticalDrug.confidence}%
Gene: ${criticalDrug.variants[0]?.gene}  |  Diplotype: ${criticalDrug.variants[0]?.diplotype}
Phenotype: ${criticalDrug.variants[0]?.phenotype}

RECOMMENDED ACTION
──────────────────
${criticalDrug.recommendation}

SUPPORTING EVIDENCE
───────────────────
Mechanism: ${criticalDrug.mechanism}
CPIC Guideline: ${criticalDrug.cpicGuideline}

ALL DRUGS SUMMARY
─────────────────
${result.drugs.map(d => `${d.drug}: ${d.riskLevel.toUpperCase()} (Conf: ${d.confidence}%)`).join('\n')}

─────────────────────────────────────────
This report was generated by PharmaGuard AI v2.4.0
CPIC v24.2  |  For clinical use under specialist supervision
`.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${result.sampleId}-executive-summary.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handlePrint = () => window.print();

    const rc = RISK_COLORS[criticalDrug.riskLevel];

    return (
        <div className="space-y-4">
            {/* Actions */}
            <div className="flex items-center gap-2">
                <motion.button
                    whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                    onClick={handleDownload}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold text-white"
                    style={{ background: 'var(--primary)' }}>
                    <Download size={12} /> Download Summary
                </motion.button>
                <motion.button
                    whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                    onClick={handlePrint}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-medium"
                    style={{ background: 'var(--bg-muted)', border: '1px solid var(--border)', color: 'var(--text-secondary)' }}>
                    <FileText size={12} /> Print View
                </motion.button>
            </div>

            {/* PDF-like report card */}
            <motion.div
                initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
                className="rounded-2xl overflow-hidden"
                style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)', boxShadow: '0 4px 24px rgba(0,0,0,0.08)' }}>

                {/* Report header bar */}
                <div className="px-6 py-4 flex items-center justify-between"
                    style={{ background: 'var(--primary)', color: 'white' }}>
                    <div>
                        <p className="text-[10px] font-mono opacity-75">PharmaGuard AI v2.4.0 · CPIC v24.2</p>
                        <p className="text-lg font-black">Executive Clinical Summary</p>
                    </div>
                    <div className="text-right text-xs opacity-80">
                        <p>{today}</p>
                        <p className="font-mono">{result.sampleId}</p>
                    </div>
                </div>

                <div className="p-6 space-y-5">
                    {/* Stats row */}
                    <div className="grid grid-cols-4 gap-3">
                        {[
                            { label: 'Overall Risk', value: `${result.overallRiskScore}/100`, color: result.overallRiskScore > 60 ? '#ef4444' : '#f59e0b' },
                            { label: 'Drugs Analysed', value: result.drugs.length, color: 'var(--primary)' },
                            { label: 'Variants', value: result.totalVariants.toLocaleString(), color: '#6366f1' },
                            { label: 'Critical', value: result.drugs.filter(d => d.severity === 'critical').length, color: '#dc2626' },
                        ].map(s => (
                            <div key={s.label} className="p-3 rounded-xl text-center"
                                style={{ background: 'var(--bg-muted)', border: '1px solid var(--border)' }}>
                                <p className="text-lg font-black" style={{ color: s.color }}>{s.value}</p>
                                <p className="text-[9px]" style={{ color: 'var(--text-secondary)' }}>{s.label}</p>
                            </div>
                        ))}
                    </div>

                    {/* Key Risk Drug */}
                    <div className="p-4 rounded-xl" style={{ background: `${rc}08`, border: `2px solid ${rc}25` }}>
                        <p className="text-[9px] font-semibold uppercase tracking-wider mb-2" style={{ color: rc }}>Key Risk Drug</p>
                        <div className="flex items-start justify-between gap-3">
                            <div className="flex-1">
                                <p className="text-base font-black" style={{ color: 'var(--text-primary)' }}>{criticalDrug.drug}</p>
                                <p className="text-[10px] font-mono" style={{ color: 'var(--text-secondary)' }}>
                                    {criticalDrug.variants[0]?.gene} · {criticalDrug.variants[0]?.diplotype} · {criticalDrug.variants[0]?.phenotype}
                                </p>
                            </div>
                            <div className="text-right flex-shrink-0">
                                <span className="px-2.5 py-1 rounded-full text-[10px] font-black"
                                    style={{ background: `${rc}15`, color: rc, border: `1px solid ${rc}30` }}>
                                    {criticalDrug.riskLevel.toUpperCase()}
                                </span>
                                <p className="text-[9px] mt-1" style={{ color: 'var(--text-secondary)' }}>{criticalDrug.confidence}% confidence</p>
                            </div>
                        </div>
                    </div>

                    {/* Recommended Action */}
                    <div className="p-4 rounded-xl" style={{ background: 'var(--bg-muted)', border: '1px solid var(--border)' }}>
                        <p className="text-[9px] font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--primary)' }}>Recommended Action</p>
                        <p className="text-xs leading-relaxed" style={{ color: 'var(--text-primary)' }}>{criticalDrug.recommendation}</p>
                    </div>

                    {/* Supporting Evidence */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div className="p-3 rounded-xl" style={{ background: 'var(--bg-muted)', border: '1px solid var(--border)' }}>
                            <p className="text-[9px] font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--text-secondary)' }}>CPIC Guideline</p>
                            <p className="text-[10px] leading-relaxed" style={{ color: 'var(--text-primary)' }}>{criticalDrug.cpicGuideline}</p>
                        </div>
                        <div className="p-3 rounded-xl" style={{ background: 'var(--bg-muted)', border: '1px solid var(--border)' }}>
                            <p className="text-[9px] font-semibold uppercase tracking-wider mb-1" style={{ color: 'var(--text-secondary)' }}>Mechanism</p>
                            <p className="text-[10px] leading-relaxed" style={{ color: 'var(--text-primary)' }}>{criticalDrug.mechanism}</p>
                        </div>
                    </div>

                    {/* All Drugs mini-ranking */}
                    <div>
                        <p className="text-[9px] font-semibold uppercase tracking-wider mb-2" style={{ color: 'var(--text-secondary)' }}>All Drugs At a Glance</p>
                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                            {result.drugs.map(d => {
                                const c = RISK_COLORS[d.riskLevel];
                                return (
                                    <div key={d.drug} className="flex items-center gap-2 p-2 rounded-lg"
                                        style={{ background: `${c}08`, border: `1px solid ${c}15` }}>
                                        <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: c }} />
                                        <div className="min-w-0">
                                            <p className="text-[10px] font-bold truncate" style={{ color: 'var(--text-primary)' }}>{d.drug}</p>
                                            <p className="text-[8px]" style={{ color: c }}>{d.riskLevel} · {d.confidence}%</p>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="flex items-center justify-between text-[8px] pt-2"
                        style={{ borderTop: '1px solid var(--border)', color: 'var(--text-muted)' }}>
                        <span>This report is generated by AI and requires clinical specialist review before action.</span>
                        <span className="font-mono">{result.sampleId} · {today}</span>
                    </div>
                </div>
            </motion.div>
        </div>
    );
};

// ─── Longitudinal Analysis Log ───────────────────────────────────────────────

const LongitudinalLog: React.FC = () => {
    const [expanded, setExpanded] = useState<string | null>(null);

    return (
        <div className="space-y-3">
            <div className="flex items-center gap-2 mb-1">
                <Clock size={14} style={{ color: 'var(--primary)' }} />
                <p className="text-xs font-bold" style={{ color: 'var(--text-primary)' }}>Longitudinal Analysis Log</p>
            </div>

            {ANALYSIS_HISTORY.map((entry, i) => {
                const isLatest = entry.isCurrent;
                const prev = ANALYSIS_HISTORY[i - 1];
                const diff = prev ? entry.overallRisk - prev.overallRisk : 0;
                const isOpen = expanded === entry.id;

                return (
                    <motion.div key={entry.id}
                        initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.07 }}
                        className="rounded-xl overflow-hidden"
                        style={{
                            border: `1px solid ${isLatest ? 'var(--primary)' : 'var(--border)'}`,
                            background: 'var(--bg-surface)',
                        }}>
                        <button onClick={() => setExpanded(isOpen ? null : entry.id)}
                            className="w-full flex items-center gap-3 px-4 py-3 text-left"
                            style={{ background: isLatest ? 'var(--primary-light)' : 'var(--bg-muted)' }}>
                            <div className="flex-1 min-w-0">
                                <div className="flex items-center gap-2">
                                    <p className="text-[11px] font-semibold font-mono" style={{ color: 'var(--text-primary)' }}>
                                        {new Date(entry.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                                    </p>
                                    {isLatest && (
                                        <span className="px-1.5 py-0.5 rounded text-[8px] font-bold"
                                            style={{ background: 'var(--primary)', color: 'white' }}>Current</span>
                                    )}
                                </div>
                                <p className="text-[9px]" style={{ color: 'var(--text-secondary)' }}>
                                    {entry.engineVersion} · {entry.cpicVersion}
                                </p>
                            </div>
                            <div className="flex items-center gap-3">
                                <div className="text-right">
                                    <p className="text-sm font-black" style={{ color: entry.overallRisk > 65 ? '#ef4444' : '#f59e0b' }}>
                                        {entry.overallRisk}
                                    </p>
                                    <p className="text-[8px]" style={{ color: 'var(--text-muted)' }}>risk score</p>
                                </div>
                                {prev && (
                                    <div className="flex items-center gap-0.5">
                                        {diff > 0
                                            ? <TrendingUp size={12} style={{ color: '#ef4444' }} />
                                            : diff < 0
                                                ? <TrendingDown size={12} style={{ color: '#10b981' }} />
                                                : <Minus size={12} style={{ color: '#6b7280' }} />}
                                        <span className="text-[9px] font-semibold"
                                            style={{ color: diff > 0 ? '#ef4444' : diff < 0 ? '#10b981' : '#6b7280' }}>
                                            {diff > 0 ? '+' : ''}{diff}
                                        </span>
                                    </div>
                                )}
                                {isOpen ? <ChevronUp size={12} style={{ color: 'var(--text-muted)' }} /> : <ChevronDown size={12} style={{ color: 'var(--text-muted)' }} />}
                            </div>
                        </button>

                        {isOpen && (
                            <motion.div
                                initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                className="px-4 py-3"
                                style={{ borderTop: '1px solid var(--border)' }}>
                                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-[10px]">
                                    <div>
                                        <p style={{ color: 'var(--text-secondary)' }}>Top Risk Drug</p>
                                        <p className="font-bold" style={{ color: 'var(--text-primary)' }}>{entry.topRiskDrug}</p>
                                    </div>
                                    <div>
                                        <p style={{ color: 'var(--text-secondary)' }}>AI Confidence</p>
                                        <p className="font-bold" style={{ color: 'var(--text-primary)' }}>{entry.confidenceScore}%</p>
                                    </div>
                                    <div>
                                        <p style={{ color: 'var(--text-secondary)' }}>Model</p>
                                        <p className="font-bold font-mono" style={{ color: 'var(--text-primary)' }}>{entry.engineVersion}</p>
                                    </div>
                                </div>
                                {prev && (
                                    <div className="mt-3 p-2 rounded-lg text-[9px]"
                                        style={{ background: diff > 0 ? '#FEF2F2' : diff < 0 ? '#ECFDF5' : 'var(--bg-muted)', border: `1px solid ${diff > 0 ? '#FECACA' : diff < 0 ? '#A7F3D0' : 'var(--border)'}` }}>
                                        {diff === 0
                                            ? '→ Risk score unchanged from previous analysis.'
                                            : diff > 0
                                                ? `⬆ Risk increased by ${diff} pts vs. ${prev.engineVersion} — review new variants.`
                                                : `⬇ Risk decreased by ${Math.abs(diff)} pts vs. ${prev.engineVersion} — intervention may be effective.`}
                                    </div>
                                )}
                            </motion.div>
                        )}
                    </motion.div>
                );
            })}
        </div>
    );
};

// ─── Main Component ──────────────────────────────────────────────────────────

const ClinicalReport: React.FC = () => {
    return (
        <div className="space-y-10">
            <div>
                <p className="text-xs font-bold mb-4 flex items-center gap-1.5" style={{ color: 'var(--text-primary)' }}>
                    <FileText size={13} style={{ color: 'var(--primary)' }} />
                    Generate Executive Summary
                </p>
                <ExecutiveClinicalReport />
            </div>
            <div style={{ borderTop: '1px solid var(--border)', paddingTop: '2rem' }}>
                <LongitudinalLog />
            </div>
        </div>
    );
};

export default ClinicalReport;
