export const SUPPORTED_DRUGS = [
    'CODEINE',
    'WARFARIN',
    'CLOPIDOGREL',
    'SIMVASTATIN',
    'AZATHIOPRINE',
    'FLUOROURACIL',
];
export const MOCK_ANALYSIS_RESULT = {
    sampleId: 'PG-2024-001847',
    timestamp: new Date().toISOString(),
    vcfFile: 'patient_genome.vcf',
    totalVariants: 4287,
    analyzedGenes: ['CYP2D6', 'CYP2C9', 'VKORC1', 'CYP2C19', 'TPMT', 'DPYD'],
    overallRiskScore: 67,
    drugs: [
        {
            drug: 'CODEINE',
            riskLevel: 'toxic',
            confidence: 94,
            severity: 'critical',
            variants: [
                {
                    gene: 'CYP2D6',
                    rsId: 'rs1065852',
                    diplotype: '*1/*1xN',
                    phenotype: 'Ultra-rapid Metabolizer',
                },
            ],
            clinicalSummary: 'Patient carries CYP2D6 ultra-rapid metabolizer phenotype. Codeine is rapidly converted to morphine at elevated rates, causing opioid toxicity and respiratory depression.',
            mechanism: 'CYP2D6 enzyme converts codeine to its active metabolite morphine via O-demethylation. Ultra-rapid metabolizers produce excessive morphine concentrations, leading to life-threatening opioid toxicity.',
            cpicGuideline: 'CPIC Grade A: Use alternative analgesic such as tramadol (with caution), morphine, or a non-opioid. Avoid codeine entirely.',
            recommendation: '⚠ CONTRAINDICATED: Do not use codeine. Switch to oxycodone or non-opioid analgesics. Monitor for opioid toxicity symptoms.',
        },
        {
            drug: 'WARFARIN',
            riskLevel: 'adjust',
            confidence: 88,
            severity: 'high',
            variants: [
                {
                    gene: 'CYP2C9',
                    rsId: 'rs1799853',
                    diplotype: '*1/*2',
                    phenotype: 'Intermediate Metabolizer',
                },
                {
                    gene: 'VKORC1',
                    rsId: 'rs9923231',
                    diplotype: 'G/A',
                    phenotype: 'Reduced Sensitivity',
                },
            ],
            clinicalSummary: 'Combined CYP2C9 intermediate metabolizer and VKORC1 variant significantly affects warfarin metabolism and sensitivity. Dose reduction of 25-40% recommended.',
            mechanism: 'CYP2C9 metabolizes the more potent S-warfarin enantiomer. Intermediate metabolizers have reduced clearance leading to drug accumulation. VKORC1 variant affects vitamin K epoxide reductase sensitivity.',
            cpicGuideline: 'CPIC Grade A: Initiate at 25-40% lower dose. Use warfarin dosing algorithm (www.warfarindosing.org). Monitor INR closely weekly for first month.',
            recommendation: '💊 DOSE REDUCTION: Start at 2.5mg instead of standard 5mg. Weekly INR monitoring for 4 weeks. Target INR 2-3 for atrial fibrillation.',
        },
        {
            drug: 'CLOPIDOGREL',
            riskLevel: 'ineffective',
            confidence: 91,
            severity: 'high',
            variants: [
                {
                    gene: 'CYP2C19',
                    rsId: 'rs4244285',
                    diplotype: '*1/*2',
                    phenotype: 'Intermediate Metabolizer',
                },
            ],
            clinicalSummary: 'Patient is a CYP2C19 intermediate metabolizer. Clopidogrel requires hepatic activation; reduced enzyme activity results in inadequate antiplatelet effect and increased cardiovascular risk.',
            mechanism: 'Clopidogrel is a prodrug requiring CYP2C19-mediated bioactivation to its active thiol metabolite. Loss-of-function variants reduce active metabolite generation, diminishing P2Y12 receptor inhibition.',
            cpicGuideline: 'CPIC Grade A: For ACS/PCI patients with IM phenotype, consider alternative antiplatelet agents (prasugrel or ticagrelor) unless contraindicated.',
            recommendation: '🔄 SWITCH THERAPY: Consider prasugrel 10mg daily or ticagrelor 90mg BID as alternative. If clopidogrel must be used, consider higher maintenance dose with platelet function testing.',
        },
        {
            drug: 'SIMVASTATIN',
            riskLevel: 'adjust',
            confidence: 79,
            severity: 'moderate',
            variants: [
                {
                    gene: 'SLCO1B1',
                    rsId: 'rs4149056',
                    diplotype: '*1/*5',
                    phenotype: 'Decreased Function',
                },
            ],
            clinicalSummary: 'SLCO1B1 decreased function variant reduces hepatic uptake of simvastatin acid, increasing plasma concentrations and myopathy risk.',
            mechanism: 'SLCO1B1 encodes the OATP1B1 transporter responsible for hepatic uptake of statins. Reduced transport leads to elevated systemic statin levels, increasing skeletal muscle exposure and myopathy risk.',
            cpicGuideline: 'CPIC Grade A: Use low-intensity simvastatin ≤20mg or switch to alternative statin (rosuvastatin/pravastatin with lower myopathy risk). Avoid simvastatin 80mg.',
            recommendation: '📉 DOSE LIMIT: Maximum simvastatin 20mg/day. Monitor for myopathy symptoms (muscle pain, weakness). Consider switching to rosuvastatin 10mg.',
        },
        {
            drug: 'AZATHIOPRINE',
            riskLevel: 'toxic',
            confidence: 97,
            severity: 'critical',
            variants: [
                {
                    gene: 'TPMT',
                    rsId: 'rs1800460',
                    diplotype: '*1/*3A',
                    phenotype: 'Intermediate Metabolizer',
                },
            ],
            clinicalSummary: 'TPMT intermediate metabolizer phenotype. Reduced TPMT activity leads to accumulation of cytotoxic thioguanine nucleotides, causing severe myelosuppression.',
            mechanism: 'TPMT inactivates 6-mercaptopurine (active azathioprine metabolite). Intermediate TPMT activity allows TGN accumulation in hematopoietic cells, causing bone marrow suppression.',
            cpicGuideline: 'CPIC Grade A: Start at 30-70% of normal dose. Monitor CBC every 2 weeks for first 3 months, then monthly. Consider NUDT15 testing for additional risk assessment.',
            recommendation: '⚠ DOSE REDUCTION: Reduce dose to 50mg (from standard 100-150mg). Minimum 2-weekly CBC monitoring. Hold medication if WBC <3.0 × 10⁹/L.',
        },
        {
            drug: 'FLUOROURACIL',
            riskLevel: 'safe',
            confidence: 83,
            severity: 'low',
            variants: [
                {
                    gene: 'DPYD',
                    rsId: 'rs3918290',
                    diplotype: '*1/*1',
                    phenotype: 'Normal Metabolizer',
                },
            ],
            clinicalSummary: 'Patient carries DPYD normal metabolizer phenotype. Standard 5-FU dosing is appropriate with routine monitoring.',
            mechanism: 'DPYD encodes dihydropyrimidine dehydrogenase, which catabolizes approximately 80% of administered 5-FU. Normal enzyme activity ensures appropriate fluorouracil clearance.',
            cpicGuideline: 'CPIC Grade A: Normal DPYD function. Administer standard dose per protocol. Routine toxicity monitoring applies.',
            recommendation: '✅ STANDARD DOSE: No dose adjustment needed. Proceed with standard 5-FU dosing per oncology protocol. Routine monitoring for fluoropyrimidine toxicity.',
        },
    ],
};
export const MOCK_GENES = {
    CYP2D6: {
        name: 'CYP2D6',
        function: 'Cytochrome P450 2D6 – metabolizes ~25% of commonly used drugs',
        pathway: 'Hepatic oxidative metabolism (Phase I)',
        affectedDrugs: ['Codeine', 'Tramadol', 'Metoprolol', 'Tamoxifen', 'Antidepressants'],
        chromosome: '22q13.2',
        variants: ['*2', '*3', '*4', '*5', '*6', '*10', '*41'],
    },
    CYP2C9: {
        name: 'CYP2C9',
        function: 'Cytochrome P450 2C9 – metabolizes warfarin, NSAIDs, sulfonylureas',
        pathway: 'Hepatic oxidative metabolism (Phase I)',
        affectedDrugs: ['Warfarin', 'Phenytoin', 'Losartan', 'NSAIDs'],
        chromosome: '10q23.33',
        variants: ['*2', '*3', '*5', '*6', '*8', '*11'],
    },
    VKORC1: {
        name: 'VKORC1',
        function: 'Vitamin K Epoxide Reductase Complex 1 – warfarin target enzyme',
        pathway: 'Vitamin K cycle / Coagulation cascade',
        affectedDrugs: ['Warfarin', 'Acenocoumarol', 'Phenprocoumon'],
        chromosome: '16p11.2',
        variants: ['rs9923231', 'rs7294'],
    },
    CYP2C19: {
        name: 'CYP2C19',
        function: 'Cytochrome P450 2C19 – activates clopidogrel, metabolizes PPIs',
        pathway: 'Hepatic bioactivation and metabolism',
        affectedDrugs: ['Clopidogrel', 'PPIs', 'Escitalopram', 'Voriconazole'],
        chromosome: '10q24.1-q24.3',
        variants: ['*2', '*3', '*17'],
    },
    TPMT: {
        name: 'TPMT',
        function: 'Thiopurine S-methyltransferase – inactivates thiopurine drugs',
        pathway: 'Thiopurine metabolism',
        affectedDrugs: ['Azathioprine', '6-Mercaptopurine', 'Thioguanine'],
        chromosome: '6p22.3',
        variants: ['*2', '*3A', '*3B', '*3C', '*4'],
    },
    DPYD: {
        name: 'DPYD',
        function: 'Dihydropyrimidine dehydrogenase – catabolizes fluoropyrimidines',
        pathway: 'Pyrimidine catabolism',
        affectedDrugs: ['5-Fluorouracil', 'Capecitabine', 'Tegafur'],
        chromosome: '1p22',
        variants: ['*2A', 'rs2297595', 'HapB3'],
    },
    SLCO1B1: {
        name: 'SLCO1B1',
        function: 'Organic Anion Transporter – hepatic uptake of statins',
        pathway: 'Drug transport (Phase III)',
        affectedDrugs: ['Simvastatin', 'Atorvastatin', 'Repaglinide', 'Methotrexate'],
        chromosome: '12p12.2',
        variants: ['*5', '*15', '*17'],
    },
};
export const GENOMIC_TIMELINE_STEPS = [
    {
        step: 1,
        label: 'Genetic Variant',
        description: 'CYP2D6 *1/*1xN detected',
        icon: '🧬',
        color: '#22d3ee',
    },
    {
        step: 2,
        label: 'Gene Expression',
        description: 'Amplified CYP2D6 gene copies',
        icon: '🔬',
        color: '#8b5cf6',
    },
    {
        step: 3,
        label: 'Enzyme Activity',
        description: 'Ultra-rapid CYP2D6 activity (>2x normal)',
        icon: '⚗️',
        color: '#f59e0b',
    },
    {
        step: 4,
        label: 'Drug Metabolism',
        description: 'Excessive codeine → morphine conversion',
        icon: '💊',
        color: '#ef4444',
    },
    {
        step: 5,
        label: 'Clinical Outcome',
        description: 'Opioid toxicity risk – respiratory depression',
        icon: '⚠️',
        color: '#ef4444',
    },
];
export const HEATMAP_DATA = [
    { gene: 'CYP2D6', codeine: 95, warfarin: 10, clopidogrel: 15, simvastatin: 5, azathioprine: 5, fluorouracil: 5 },
    { gene: 'CYP2C9', codeine: 5, warfarin: 85, clopidogrel: 20, simvastatin: 30, azathioprine: 5, fluorouracil: 5 },
    { gene: 'VKORC1', codeine: 5, warfarin: 75, clopidogrel: 5, simvastatin: 5, azathioprine: 5, fluorouracil: 5 },
    { gene: 'CYP2C19', codeine: 10, warfarin: 10, clopidogrel: 90, simvastatin: 15, azathioprine: 5, fluorouracil: 5 },
    { gene: 'TPMT', codeine: 5, warfarin: 5, clopidogrel: 5, simvastatin: 5, azathioprine: 97, fluorouracil: 10 },
    { gene: 'DPYD', codeine: 5, warfarin: 5, clopidogrel: 5, simvastatin: 5, azathioprine: 5, fluorouracil: 15 },
    { gene: 'SLCO1B1', codeine: 5, warfarin: 15, clopidogrel: 10, simvastatin: 80, azathioprine: 5, fluorouracil: 5 },
];
export const RADAR_DATA = [
    { subject: 'Efficacy', codeine: 20, warfarin: 75, clopidogrel: 30, simvastatin: 70, azathioprine: 45, fluorouracil: 85 },
    { subject: 'Safety', codeine: 15, warfarin: 55, clopidogrel: 40, simvastatin: 65, azathioprine: 30, fluorouracil: 80 },
    { subject: 'Metabolism', codeine: 90, warfarin: 70, clopidogrel: 65, simvastatin: 60, azathioprine: 85, fluorouracil: 75 },
    { subject: 'Toxicity', codeine: 95, warfarin: 55, clopidogrel: 30, simvastatin: 40, azathioprine: 90, fluorouracil: 20 },
    { subject: 'Dosing', codeine: 10, warfarin: 60, clopidogrel: 35, simvastatin: 65, azathioprine: 45, fluorouracil: 85 },
];
export const RISK_COLORS = {
    safe: '#10b981',
    adjust: '#f59e0b',
    toxic: '#ef4444',
    ineffective: '#3b82f6',
    unknown: '#6b7280',
};
export const RISK_LABELS = {
    safe: '✅ Safe',
    adjust: '⚠️ Adjust Dosage',
    toxic: '🔴 Toxic',
    ineffective: '🔵 Ineffective',
    unknown: '⚪ Unknown',
};
export const SEVERITY_COLORS = {
    low: '#10b981',
    moderate: '#f59e0b',
    high: '#f97316',
    critical: '#ef4444',
};
